.zhihu.:
  must_contain_parts:
    - p
feministcurrent:
  not_contain:
    - podcast
    - whats-current
wemp.app:
  must_contain_parts:
    - posts
ed.ted.com:
  must_contain_parts:
    - lessons
gonghao51:
  not_contain:
    - guaishi
medium:
  signature: true